name: MLOps CI/CD

on:
  push:
    branches:
      - main  # on peut ajuster la branche ici

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Spécifiez la version de Python nécessaire

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # TODO : Exécutez les tests ici

    - name: Run notebook
      run: |
        chmod +x run_notebook.sh
        ./run_notebook.sh

    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Ajoutez d'autres étapes comme la formation de modèles, le déploiement, etc.

