name: MLOps CI/CD

on:
  push:
    branches:
      - main  # on peut ajuster la branche ici
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MLFLOW_SERVER_USERNAME: ${{ secrets.MLFLOW_SERVER_USERNAME }}
      MLFLOW_SERVER_PASSWORD: ${{ secrets.MLFLOW_SERVER_PASSWORD }} 

    steps:

    - name: ENV VARIABLES
      run: |
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
        echo "MLFLOW_SERVER_USERNAME: $MLFLOW_SERVER_USERNAME"
        echo "MLFLOW_SERVER_PASSWORD: $MLFLOW_SERVER_PASSWORD"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Spécifiez la version de Python nécessaire

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # List installed dependencies and their versions
        pip freeze > installed_dependencies.txt

    - name: Display installed dependencies
      run: cat installed_dependencies.txt

    - name: Run tests
      run: |
        pytest

    - name: Run notebook
      run: |
        chmod +x run_notebook.sh
        ./run_notebook.sh

    #- name: Run Super-Linter
      #uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Ajoutez d'autres étapes comme la formation de modèles, le déploiement, etc.